### ISSUE TITLE
Order of the names listed in font-family make a huge impact on rendering

### ISSUE THREAD

**Issue by jonathansp** [openhtmltopdf/openhtmltopdf#41]
I've been testing the support for CJK (noto sans cjk) and latin (open sans) mixed.

I realised the order I declare the fonts in a css `font-family` block has a massive impact on the rendering time and performance. For example: a 2mb html that mainly has Chinese text, when declared as:

```css
body { font-family: 'noto sans cjk', 'open sans'; }
```
renders in ~3 seconds.

if I just change the order to:

```css
body { font-family: 'open sans', 'noto sans cjk'; }
```
**it took ~12 seconds.** Same document without changes.

Also, I was able to simulate the same issue on the sandbox.

Steps to:

1. Open https://sandbox.openhtmltopdf.com/?file=cjk.htm
2. Duplicate the Chinese or Japanese block several times until you get a ~15 pages PDF.
3. Monitoring your networking using any tool and see that the http request takes around 600ms (my vary but usually is consistent).
4. Change the CSS font family order, making 'deja-sans' as the first font.
5. Repeat the request and you'll see it takes something around 1.2s or twice the first request.

Is there any workaround as it has been impacting a lot out systems? In my local tests, this is a pretty regular behaviour when using font fallbacks.

Version: io.github.openhtmltopdf version 1.1.12 

```java
      // my current snippet.
      PdfRendererBuilder builder = new PdfRendererBuilder()
          .useCacheStore(CacheStore.PDF_FONT_METRICS, cache)
          .withW3cDocument(parseDocument(body), null)
          .usePdfUaAccessbility(true)
          .usePdfAConformance(PdfAConformance.PDFA_3_U)
          .useSVGDrawer(drawer)
          .useMathMLDrawer(drawer)
          // useFont(... local ttf fonts here ...)
          .toStream(os);

```

**Comment by siegelzc** [comment]
May be unrelated, but if you're setting the PDFA conformance, I believe the fonts should be manually supplied, rather than relying on the system.

**Comment by siegelzc** [comment]
Have you used a profiler on it?

**Comment by jonathansp** [comment]
According to my tests, accessibility, pdf/a, CSS 3 transformation, @page rules don't change change the behaviour. Noto Sans ttf was downloaded from Google Webfonts (I omitted to save space). I haven't profiled it though.

**Comment by jonathansp** [comment]
> May be unrelated, but if you're setting the PDFA conformance, I believe the fonts should be manually supplied, rather than relying on the system.

Yes, supplied as part of the classpath using useFont method.

**Comment by jonathansp** [comment]
I can see `org.apache.pdfbox.pdmodel.font.PDFont.encode()` calling several time `PDCIDFontType2.encode()` and throwing `throw new IllegalArgumentException(String.format("No glyph for U+%04X (%c) in font %s", unicode, (char)unicode, this.getName()));`

Working fine:
![3s](https://github.com/openhtmltopdf/openhtmltopdf/assets/457972/4454c6c1-cd9e-4dc8-b261-0fa5334e9073)

Issue:
![11s](https://github.com/openhtmltopdf/openhtmltopdf/assets/457972/9788e53e-7410-42d6-ae59-fa05a9576f50)

**Comment by siegelzc** [comment]
Can you send me the HTML file you're using?

**Comment by siegelzc** [comment]
I agree, this looks to be the issue.

**Comment by siegelzc** [comment]
The renderer is going to try to render unsupported characters within a string by resorting to the fallback fonts specified in the font-family declaration. It scans through the entire string character-by-character to find where certain regions of text can be rendered by each font, splitting the string into sub-strings.

This inefficiency is a feature, not a bug, but perhaps the slowdown can be minimized by an optimization via 'chunking'.

```
int min_chunk_size;
int chunk_ratio;

getWidth(str):
  try {
    return font.getStringWidth(str)
  } catch (IllegalArgumentException e) {
    List<String> chunks = split <str> into <chunk_ratio>-many partitions
    if (chunks.get(0).length() >= min_chunk_size) {
      return chunks.stream().map(this::getWidth).reduce(Integer::sum)      
    }
    // if chunks would be smaller than min, do not chunk

    return getStringWidthSlow(str)
  }

**Comment by siegelzc** [comment]
I'll take care of the implementation. I already have a branch with some minor refactoring that helped me to read the code.

**Comment by jonathansp** [comment]
hey @siegelzc have you had a chance to look into this?

**Comment by siegelzc** [comment]
@jonathansp Sorry for the delay. I'm trying to help my brother get back into programming, and I thought this would be a good ticket for him to ramp up with, so I was waiting for him to become available to work with me on it. I went ahead and implemented the aforementioned partitioning strategy in #53 .

**Comment by siegelzc** [comment]
I've updated the code with a couple bug fixes. Could you re-run the profiler with my branch cloned (I don't have the relevant fonts)?

**Comment by siegelzc** [comment]
I merged #53, so I'm closing this issue. If the problem persists we can reconvene and reopen the issue.

**Comment by jonathansp** [comment]
hey @siegelzc thank you for your work on this. Is this version released yet?

**Comment by siegelzc** [comment]
https://github.com/openhtmltopdf/openhtmltopdf/releases/tag/20240630051703

**Comment by jonathansp** [comment]
hey @siegelzc I've tested with v1.1.19 and unfortunately the problem still happening.

**Comment by siegelzc** [comment]
nvm, re-closing this.
see #64
